import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The handbook sidebar is defined explicitly rather than generated from the
 * filesystem, for two reasons:
 *
 * 1. **Domain grouping.** Topics are grouped by what they are used for rather
 *    than by where their files sit on disk. Achieving this with an autogenerated
 *    sidebar would require moving directories, changing published URLs.
 * 2. **Pedagogical ordering.** Pages are ordered the way you would learn them —
 *    concepts, then commands, then practices, then pitfalls — not alphabetically.
 *
 * Every topic sits in one of eleven top-level sections, ordered along the
 * lifecycle of a project: what you need to know, what you build with, how you
 * design it, and how you ship and run it. Sections are top-level rather than
 * nested under a single "Knowledge Base" parent, because a parent that contains
 * *everything* adds a level of indentation without adding information.
 *
 * The sections mirror those in `ROADMAP.md`, which is the source of truth for
 * what the handbook intends to cover. Keep the two in step.
 *
 * When adding a page, add it here — it will not appear automatically, and the
 * build warns about any doc missing from the sidebar.
 */

/** A page, with an explicit sidebar label distinct from its front-matter title. */
function doc(id: string, label: string) {
  return {type: 'doc' as const, id, label};
}

/** A section landing page listing its children as cards. */
function overview(slug: string, title: string, description: string) {
  return {type: 'generated-index' as const, slug, title, description};
}

const sidebars: SidebarsConfig = {
  handbookSidebar: [
    'introduction',
    {type: 'doc', id: 'knowledge-base/knowledge-base', label: 'All Topics'},

    // ------------------------------------------------------- Fundamentals
    {
      type: 'category',
      label: 'Fundamentals',
      link: overview(
        '/knowledge-base/fundamentals',
        'Fundamentals',
        'Platform and engineering basics that everything else in the handbook builds on.',
      ),
      items: [
        doc('knowledge-base/general/how-code-runs', 'How Code Runs'),
        doc(
          'knowledge-base/general/data-representation',
          'Data Representation',
        ),
        doc('knowledge-base/general/concurrency', 'Concurrency & Async'),
        doc('knowledge-base/general/complexity-and-cost', 'Complexity & Cost'),
        doc(
          'knowledge-base/general/idempotency-and-state',
          'Idempotency & State',
        ),
        doc(
          'knowledge-base/general/designing-for-change',
          'Designing for Change',
        ),
        doc(
          'knowledge-base/general/versioning-and-configuration',
          'Versioning & Configuration',
        ),
        {type: 'doc', id: 'knowledge-base/dom/dom', label: 'DOM'},
        {type: 'doc', id: 'knowledge-base/testing/index', label: 'Testing'},
      ],
    },

    // ---------------------------------------------------- Developer Tools
    {
      type: 'category',
      label: 'Developer Tools',
      link: overview(
        '/knowledge-base/developer-tools',
        'Developer Tools',
        'Version control, package managers, containers and remote access — the tools you touch every day.',
      ),
      items: [
        {
          type: 'category',
          label: 'Git',
          link: {type: 'doc', id: 'knowledge-base/git/index'},
          items: [
            'knowledge-base/git/key-concepts',
            {
              type: 'doc',
              id: 'knowledge-base/git/git-commands',
              label: 'Commands',
            },
            'knowledge-base/git/best-practices',
            'knowledge-base/git/common-mistakes',
          ],
        },
        {
          type: 'category',
          label: 'npm',
          link: {type: 'doc', id: 'knowledge-base/npm/index'},
          items: [
            'knowledge-base/npm/key-concepts',
            {
              type: 'doc',
              id: 'knowledge-base/npm/npm-commands',
              label: 'Commands',
            },
            'knowledge-base/npm/best-practices',
            'knowledge-base/npm/common-mistakes',
          ],
        },
        doc('knowledge-base/pnpm/index', 'pnpm'),
        doc('knowledge-base/yarn/index', 'Yarn'),
        {
          type: 'category',
          label: 'Composer',
          link: {type: 'doc', id: 'knowledge-base/composer/index'},
          items: [
            'knowledge-base/composer/key-concepts',
            {
              type: 'doc',
              id: 'knowledge-base/composer/composer-commands',
              label: 'Commands',
            },
          ],
        },
        doc('knowledge-base/docker/index', 'Docker'),
        doc('knowledge-base/docker-compose/index', 'Docker Compose'),
        doc('knowledge-base/ssh/index', 'SSH'),
      ],
    },

    // ---------------------------------------------------------- Frontend
    {
      type: 'category',
      label: 'Frontend',
      link: overview(
        '/knowledge-base/frontend',
        'Frontend',
        'Libraries and frameworks for building user interfaces, and the practices that keep them fast and maintainable.',
      ),
      items: [
        {
          type: 'category',
          label: 'React',
          link: {type: 'doc', id: 'knowledge-base/react-js/index'},
          items: [
            'knowledge-base/react-js/component-design',
            'knowledge-base/react-js/state-management',
            'knowledge-base/react-js/best-practices',
            'knowledge-base/react-js/common-mistakes',
          ],
        },
        {
          type: 'category',
          label: 'Next.js',
          link: {type: 'doc', id: 'knowledge-base/next-js/index'},
          items: [
            'knowledge-base/next-js/folder-structure',
            {
              type: 'doc',
              id: 'knowledge-base/next-js/server-side-rendering',
              label: 'Rendering & SSR',
            },
            'knowledge-base/next-js/api-routes',
            {type: 'doc', id: 'knowledge-base/next-js/seo', label: 'SEO'},
            'knowledge-base/next-js/best-practices',
            'knowledge-base/next-js/common-misconceptions',
            'knowledge-base/next-js/common-mistakes',
          ],
        },
        doc('knowledge-base/react-native/index', 'React Native'),
        doc('knowledge-base/flutter/index', 'Flutter'),
      ],
    },

    // ----------------------------------------------------------- Backend
    {
      type: 'category',
      label: 'Backend',
      link: overview(
        '/knowledge-base/backend',
        'Backend',
        'Server-side frameworks and platforms for building APIs and web applications.',
      ),
      items: [
        doc('knowledge-base/express/index', 'Express'),
        doc('knowledge-base/laravel/index', 'Laravel'),
        doc('knowledge-base/fastapi/index', 'FastAPI'),
        doc('knowledge-base/wordpress/index', 'WordPress'),
      ],
    },

    // --------------------------------------------------------- Databases
    {
      type: 'category',
      label: 'Databases',
      link: overview(
        '/knowledge-base/databases',
        'Databases',
        'Relational, document and in-memory data stores, and the modelling decisions that determine how well they perform.',
      ),
      items: [
        doc('knowledge-base/databases/data-modelling', 'Data Modelling'),
        doc('knowledge-base/databases/postgresql', 'PostgreSQL'),
        doc('knowledge-base/databases/mysql', 'MySQL'),
        doc('knowledge-base/databases/sqlite', 'SQLite'),
        doc('knowledge-base/databases/mongodb', 'MongoDB'),
        doc('knowledge-base/redis/index', 'Redis'),
      ],
    },

    // -------------------------------------------------------------- APIs
    {
      type: 'category',
      label: 'APIs',
      link: overview(
        '/knowledge-base/apis',
        'APIs',
        'Designing and consuming the interfaces between systems, from request/response to realtime.',
      ),
      items: [
        doc('knowledge-base/apis/rest', 'REST APIs'),
        doc('knowledge-base/apis/graphql', 'GraphQL'),
        doc('knowledge-base/apis/openapi', 'OpenAPI'),
        doc('knowledge-base/apis/pagination', 'Pagination'),
        doc('knowledge-base/apis/webhooks', 'Webhooks'),
        doc('knowledge-base/apis/websockets', 'WebSockets'),
        doc('knowledge-base/apis/server-sent-events', 'Server-Sent Events'),
      ],
    },

    // ------------------------------------------------------ Architecture
    {
      type: 'category',
      label: 'Architecture',
      link: overview(
        '/knowledge-base/architecture',
        'Architecture',
        'Structuring systems so they stay changeable as they grow.',
      ),
      items: [
        doc('knowledge-base/architecture/mvc', 'MVC'),
        doc(
          'knowledge-base/architecture/clean-architecture',
          'Clean Architecture',
        ),
        doc('knowledge-base/architecture/solid', 'SOLID Principles'),
        doc('knowledge-base/architecture/design-patterns', 'Design Patterns'),
        doc(
          'knowledge-base/architecture/dependency-injection',
          'Dependency Injection',
        ),
        doc('knowledge-base/architecture/monoliths', 'Monoliths'),
        doc('knowledge-base/architecture/microservices', 'Microservices'),
        doc('knowledge-base/architecture/event-driven', 'Event-Driven'),
      ],
    },

    // ---------------------------------------------------------- Security
    {
      type: 'category',
      label: 'Security',
      link: overview(
        '/knowledge-base/security',
        'Security',
        'The vulnerabilities that actually appear in production, and how to prevent them.',
      ),
      items: [
        doc('knowledge-base/security/authentication', 'Authentication'),
        doc('knowledge-base/security/authorization', 'Authorization'),
        doc(
          'knowledge-base/security/sessions-and-cookies',
          'Sessions & Cookies',
        ),
        doc('knowledge-base/security/jwt', 'JWT'),
        doc('knowledge-base/security/oauth', 'OAuth 2.1 & OIDC'),
        doc('knowledge-base/security/cors', 'CORS'),
        doc('knowledge-base/security/xss', 'XSS'),
        doc('knowledge-base/security/csrf', 'CSRF'),
        doc('knowledge-base/security/sql-injection', 'SQL Injection'),
        doc('knowledge-base/security/checklist', 'Checklist'),
      ],
    },

    // ---------------------------------------------------- Web Essentials
    {
      type: 'category',
      label: 'Web Essentials',
      link: overview(
        '/knowledge-base/web',
        'Web Essentials',
        'Cross-cutting concerns every user-facing application has to get right.',
      ),
      items: [
        doc('knowledge-base/web/performance', 'Performance'),
        doc('knowledge-base/web/accessibility', 'Accessibility'),
        doc('knowledge-base/web/seo', 'SEO'),
        doc('knowledge-base/web/file-uploads', 'File Uploads'),
        doc('knowledge-base/web/email', 'Email Systems'),
        doc('knowledge-base/web/search', 'Search'),
      ],
    },

    // --------------------------------------------- Hosting & Deployment
    {
      type: 'category',
      label: 'Hosting & Deployment',
      link: overview(
        '/knowledge-base/hosting',
        'Hosting & Deployment',
        'Getting an application onto the internet and keeping it reachable, secure and fast.',
      ),
      items: [
        doc('knowledge-base/hosting/dns', 'DNS'),
        doc('knowledge-base/hosting/ssl-tls', 'SSL/TLS'),
        doc('knowledge-base/hosting/nginx', 'Nginx'),
        doc('knowledge-base/hosting/reverse-proxy', 'Reverse Proxy'),
        doc('knowledge-base/hosting/cdn', 'CDN'),
        doc('knowledge-base/cloudflare/index', 'Cloudflare'),
        doc('knowledge-base/hosting/vps', 'VPS'),
        doc('knowledge-base/hosting/aws', 'AWS'),
        doc('knowledge-base/hosting/digitalocean', 'DigitalOcean'),
        doc('knowledge-base/hosting/hetzner', 'Hetzner'),
        doc('knowledge-base/hosting/cpanel', 'cPanel'),
        doc('knowledge-base/hosting/ci-cd', 'CI/CD'),
        doc('knowledge-base/hosting/github-actions', 'GitHub Actions'),
      ],
    },

    // -------------------------------------------------------- Operations
    {
      type: 'category',
      label: 'Operations',
      link: overview(
        '/knowledge-base/operations',
        'Operations',
        'Running software in production: knowing what it is doing, and keeping it responsive.',
      ),
      items: [
        doc('knowledge-base/operations/logging', 'Logging'),
        doc('knowledge-base/operations/monitoring', 'Monitoring'),
        doc('knowledge-base/operations/observability', 'Observability'),
        doc('knowledge-base/operations/opentelemetry', 'OpenTelemetry'),
        doc('knowledge-base/operations/prometheus', 'Prometheus'),
        doc('knowledge-base/operations/grafana', 'Grafana'),
        doc('knowledge-base/operations/caching', 'Caching'),
        doc('knowledge-base/operations/queues', 'Queues'),
        doc(
          'knowledge-base/operations/background-workers',
          'Background Workers',
        ),
        doc('knowledge-base/kafka/index', 'Apache Kafka'),
      ],
    },
  ],
};

export default sidebars;
