import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * The sidebar is generated from the filesystem structure of `developer-handbook/`.
 *
 * Ordering and labels are controlled per-directory via `_category_.json` files
 * and per-page via the `sidebar_position` / `sidebar_label` front matter, which
 * keeps navigation co-located with the content it describes.
 */
const sidebars: SidebarsConfig = {
  handbookSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
